version: "3.8"

services:
  database:
    container_name: Database
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_USER: dev
      MYSQL_PASSWORD: developer
      MYSQL_DATABASE: steaklasagne
    ports:
      - "3306:3306"