name: SonarCloud Scan

on:
  pull_request:
    branches:
      - "develop"
      - "feature/*"

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sl-server

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Analyze With SonarCloud
        uses: sonarsource/sonarcloud-github-actions@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=SL-Server
            -Dsonar.organization=jayreturns